var html = {
    initiate_load:
    [
        '<!DOCTYPE html>',
        '<html>',
            '<head>',
                '<title>Test</title>',
                '<style>',
                  '#test p {',
                      'margin-top: 25px;',
                      'font-size: 21px;',
                      'text-align: center;',
                      'animation: fadein 5s;',
                      '-moz-animation: fadein 5s; /* Firefox */',
                      '-webkit-animation: fadein 5s; /* Safari and Chrome */',
                      '-o-animation: fadein 5s; /* Opera */',
                  '}',
                  '@keyframes fadein {',
                      'from {',
                          'opacity:0;',
                      '}',
                      'to {',
                          'opacity:1;',
                      '}',
                  '}',
                  '@-moz-keyframes fadein { /* Firefox */',
                      'from {',
                          'opacity:0;',
                      '}',
                      'to {',
                          'opacity:1;',
                      '}',
                  '}',
                  '@-webkit-keyframes fadein { /* Safari and Chrome */',
                      'from {',
                          'opacity:0;',
                      '}',
                      'to {',
                          'opacity:1;',
                      '}',
                  '}',
                  '@-o-keyframes fadein { /* Opera */',
                      'from {',
                          'opacity:0;',
                      '}',
                      'to {',
                          'opacity: 1;',
                      '}',
                  '}',
                '</style>',
            '</head>',
            '<body>',
              '<div id="test">',
              '<p>MF test niggah</p>',
              '</div>',
            '</body>',
        '</html>'
    ].join("")
};

alert('Welcome back, ' + username);
document.write(html.initiate_load);